# Phân tích dữ liệu MIND và tạo vector biểu diễn

Notebook này chuẩn bị dữ liệu tin tức, tạo vector cho từng tin và tổng hợp thành vector của người dùng.

## 1. Thiết lập môi trường

Import các thư viện cần dùng và cấu hình cách hiển thị số.

Import primary library

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from IPython.display import display
import json

np.set_printoptions(
    precision=4,  # 4 chữ số thập phân
    suppress=True,  # không dùng dạng 1.23e-05
    linewidth=200,  # tránh xuống dòng quá sớm
)

### Công cụ xử lý dữ liệu

Nạp các thư viện để tải dữ liệu, thao tác tệp và tạo đặc trưng từ văn bản.

In [2]:
import os
# import kagglehub
import shutil
from sklearn.feature_extraction.text import CountVectorizer

## 2. Tải và chuẩn bị dữ liệu

Tải bộ MIND, lưu các tệp cần thiết vào thư mục làm việc và tạo mẫu dữ liệu nhỏ.

Load Data

In [3]:
# path = kagglehub.dataset_download("arashnic/mind-news-dataset")

# print("Dataset downloaded to: ", path)

Copy data to working dir

In [4]:
# source = os.path.join(path, "MINDsmall_train")

# destination = r"D:\CDNC\MIND-research\data\raw"

# os.makedirs(destination, exist_ok=True)

# files = [
#     "news.tsv",
#     "behaviors.tsv",
#     "entity_embedding.vec",
#     "relation_embedding.vec",
# ]

# for file in files:
#     shutil.copy2(os.path.join(source, file), os.path.join(destination, file))

# print("Done")

## 3. Chuẩn bị lịch sử đọc và tin tức

Chọn một nhóm người dùng mẫu, lấy các tin họ đã đọc và lọc thông tin tin tức tương ứng.

**Prepare users behavious dataset**

In [5]:
# behaviours_path = os.path.join(destination, "behaviors.tsv")

# columns_behaviours = ["user_id", "time", "history", "impressions"]

# behaviours = pd.read_csv(
#     behaviours_path,
#     sep="\t",
#     names=columns_behaviours,
# )

# behaviours = behaviours[["user_id", "history"]]
# behaviours = behaviours.dropna(subset=["history"])

# # sample_behaviours = behaviours.sample(n=10, random_state=42).reset_index(drop=True)

# output_dir = r"D:\CDNC\MIND-research\data\sample"

# behaviours.to_csv(os.path.join(output_dir, "behaviours.csv"), index=False)

# print(behaviours.head())

**Get all readed news in user behaviours dataset**

In [6]:
# user_behaviours = behaviours.set_index("user_id")["history"].to_dict()
# all_readed_news = set()

# for key, value in user_behaviours.items():
#     [all_readed_news.add(i) for i in value.split()]

# print(len(all_readed_news))

**Get news dataset**

In [7]:
# news_path = os.path.join(destination, "news.tsv")

# if not os.path.exists(news_path):
#     f_news_small = open(news_path, "x", encoding="utf-8")


# columns = [
#     "News_ID",
#     "Category",
#     "SubCategory",
#     "Title",
#     "Abstract",
#     "URL",
#     "Title_Entities",
#     "Abstract_Entities",
# ]

# news = pd.read_csv(
#     news_path,
#     sep="\t",
#     names=columns,
# )

# news = news[["News_ID", "Category", "Title"]]

# # sample_news = news[news["News_ID"].isin(all_readed_news)].reset_index(drop=True)

# output_dir = r"D:\CDNC\MIND-research\data\sample"

# news.to_csv(os.path.join(output_dir, "news.csv"), index=False)

# print(news.shape)
# print(news.head())

## 4. Khởi tạo mô hình

Khởi tạo mô hình embedding câu, mô hình chủ đề và nơi lưu các kết quả vector.

In [8]:
from sentence_transformers import SentenceTransformer
from bertopic import BERTopic


class Models:
    def __init__(self):
        self.sentence_model = SentenceTransformer("all-MiniLM-L6-v2")

        self.svectorizer = CountVectorizer(
            stop_words="english",
        )

        self.topic_model = BERTopic(
            calculate_probabilities=True,  # Important to set this to True for probability calculations
            verbose=True,
            vectorizer_model=self.svectorizer,
        )


models = Models()


class VectorContext:
    def __init__(self):
        self.title_list = None
        self.semantic_vector_list = None
        self.probabilities_list = None
        self.topics_vector_list = None

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

## 5. Tạo vector biểu diễn cho tin tức

Mỗi tin được biểu diễn theo ngữ nghĩa của tiêu đề và phân bố chủ đề.

### Vector Factory

`VectorFactory` được sử dụng để tạo đối tượng biểu diễn vector tương ứng với từng mô hình thông qua một giao diện thống nhất. Thay vì khởi tạo trực tiếp từng lớp, người dùng chỉ cần chỉ định loại mô hình (`sentence` hoặc `bertopic`), Factory sẽ trả về đối tượng phù hợp.

Thiết kế này giúp:

- Tách biệt logic khởi tạo khỏi logic xử lý.
- Dễ dàng thay thế hoặc mở rộng sang các mô hình mới mà không ảnh hưởng đến mã nguồn hiện có.
- Tăng khả năng bảo trì và tái sử dụng mã nguồn.

Vector Interface

In [9]:
from abc import ABC, abstractmethod


class Vector(ABC):
    @abstractmethod
    def get_vector(self):
        pass

    @abstractmethod
    def overview(self):
        pass

    @abstractmethod
    def summary(self):
        pass

Semantic vector

In [10]:
class SentenceVector(Vector):
    def __init__(self, model):
        self.model = model
        self.semantic_vector = None

    def get_vector(self, title_list):
        self.title_list = title_list

        titles = [news["title"] for news in title_list]

        vectors = self.model.encode(
            titles, show_progress_bar=True, convert_to_numpy=True
        )

        self.semantic_vector = {
            news["news_id"]: vector for news, vector in zip(title_list, vectors)
        }
        return self.semantic_vector

    def overview(self):
        print("=" * 60)
        print("Sentence Embedding Overview")
        print(f"[Sentence is: {list(self.semantic_vector.keys())[0]}]")
        print("=" * 60)

        print(f"Documents : {len(self.semantic_vector)}")
        print(
            f"Dimension : {self.semantic_vector[list(self.semantic_vector.keys())[0]].shape[0]}"
        )
        print(
            f"Shape     : {self.semantic_vector[list(self.semantic_vector.keys())[0]].shape}"
        )

        print("\nFirst vector (first 10 values):")
        print(self.semantic_vector[list(self.semantic_vector.keys())[0]][:10], "...")

    def summary(self, sample_index=0):

        sample = self.title_list[sample_index]

        news_id = sample["news_id"]
        title = sample["title"]

        vector = self.semantic_vector[news_id]

        metrics = pd.DataFrame(
            {
                "Metric": [
                    "Embedding Model",
                    "Number of Documents",
                    "Embedding Dimension",
                    "Output Shape",
                ],
                "Value": [
                    self.model.__class__.__name__,
                    len(self.semantic_vector),
                    vector.shape[0],
                    str(vector.shape),
                ],
            }
        )

        vector_preview = ", ".join(f"{x:.4f}" for x in vector[:10]) + ", ..."

        example = pd.DataFrame(
            {
                "News ID": [news_id],
                "Sample Title": [title],
                "Embedding (first 10 dims)": [f"[{vector_preview}]"],
            }
        )

        return metrics, example

Topic vector

In [11]:
class BERTopicVector(Vector):
    def __init__(self, model):
        self.model = model

        self.notice = (
            "BERTopic depends on the sentence transformer model."
            " Please ensure that the sentence transformer model is trained before using BERTopic."
        )

        self.probabilities = None
        self.topics_vector = None

    def get_vector(self, title_list, semantic_vector=None):
        self.title_list = title_list

        titles = [news["title"] for news in title_list]

        embeddings = np.array([semantic_vector[news["news_id"]] for news in title_list])

        if semantic_vector is None:
            print(self.notice)
            return

        topics, probabilities = self.model.fit_transform(
            titles,
            embeddings,
        )

        self.topic_vector = {
            news["news_id"]: {"topic": topic, "probability": probability}
            for news, topic, probability in zip(title_list, topics, probabilities)
        }

        return self.topic_vector

    def overview(self):

        print("=" * 60)
        print("BERTopic Overview")
        print("=" * 60)

        print(f"Number of documents : {len(self.title_list)}")
        print(
            f"Number of topics    : {len(set(v['topic'] for v in self.topic_vector.values()) - {-1})}"
        )

        print("\nTopic distribution:")
        print(self.model.get_topic_info()[["Topic", "Count"]])

        print("\nFirst 5 documents:")

        for sample in self.title_list[:5]:

            news_id = sample["news_id"]
            title = sample["title"]

            topic = self.topic_vector[news_id]["topic"]

            print(f"{news_id}")
            print(f"Title : {title}")
            print(f"Topic : {topic}")
            print("-" * 40)

        first_probability = next(iter(self.topic_vector.values()))["probability"]

        print("\nProbability shape:")
        print(first_probability.shape)

        print("\nFirst 5 probability vectors:")

        for sample in self.title_list[:5]:

            news_id = sample["news_id"]

            probability = self.topic_vector[news_id]["probability"]

            preview = ", ".join(f"{p:.4f}" for p in probability[:10])

            print(f"{news_id} -> [{preview}, ...]")

    def summary(self, sample_index=0):

        # =========================
        # Metrics
        # =========================

        topics = [value["topic"] for value in self.topic_vector.values()]

        first_probability = next(iter(self.topic_vector.values()))["probability"]

        metrics_df = pd.DataFrame(
            {
                "Metric": [
                    "Topic Model",
                    "Number of Documents",
                    "Number of Topics",
                    "Number of Outliers",
                    "Probability Shape",
                ],
                "Value": [
                    self.model.__class__.__name__,
                    len(self.title_list),
                    len(set(topics) - {-1}),
                    np.sum(np.array(topics) == -1),
                    str(first_probability.shape),
                ],
            }
        )

        # =========================
        # Topic Information
        # =========================

        topic_df = self.model.get_topic_info()[["Topic", "Count"]].copy()

        keywords = []

        for topic in topic_df["Topic"]:

            if topic == -1:
                keywords.append("Outlier")
            else:
                words = [word for word, _ in self.model.get_topic(topic)[:5]]
                keywords.append(", ".join(words))

        topic_df["Top Keywords"] = keywords

        # =========================
        # Sample
        # =========================

        sample = self.title_list[sample_index]

        news_id = sample["news_id"]
        title = sample["title"]

        topic_info = self.topic_vector[news_id]

        probs = ", ".join(f"{p:.4f}" for p in topic_info["probability"])

        sample_df = pd.DataFrame(
            {
                "News ID": [news_id],
                "Sample Title": [title],
                "Assigned Topic": [topic_info["topic"]],
                "Probability Distribution": [f"[{probs}]"],
            }
        )

        return metrics_df, topic_df, sample_df

Title list

In [12]:
destination = r"D:\CDNC\MIND-research\data\raw"
news_path = os.path.join(destination, "news.tsv")

if not os.path.exists(news_path):
    f_news_small = open(news_path, "x", encoding="utf-8")


columns = [
    "News_ID",
    "Category",
    "SubCategory",
    "Title",
    "Abstract",
    "URL",
    "Title_Entities",
    "Abstract_Entities",
]

news = pd.read_csv(
    news_path,
    sep="\t",
    names=columns,
)

news = news[["News_ID", "Category", "Title"]]

model_context = VectorContext()
model_context.title_list = (
    news.rename(columns={
        "News_ID": "news_id",
        "Title": "title"
    })[["news_id", "title"]]
    .to_dict("records")
)
# print(model_context.title_list)

Semantic vector

In [13]:
sentence_vector = SentenceVector(models.sentence_model)

model_context.semantic_vector_list = sentence_vector.get_vector(
    model_context.title_list
)
# print(model_context.semantic_vector_list)
sentence_vector.overview()

metric, example = sentence_vector.summary()

print("\nSummary of Sentence Embedding:")
display(metric)
print("\nExample of Sentence Embedding:")
display(example)

Batches:   0%|          | 0/1603 [00:00<?, ?it/s]

============================================================
Sentence Embedding Overview
[Sentence is: N55528]
============================================================
Documents : 51282
Dimension : 384
Shape     : (384,)

First vector (first 10 values):
[-0.0093  0.0424  0.059   0.0121  0.0334  0.0196  0.0274 -0.0615 -0.0362 -0.039 ] ...

Summary of Sentence Embedding:

                Metric                Value
0      Embedding Model  SentenceTransformer
1  Number of Documents                51282
2  Embedding Dimension                  384
3         Output Shape               (384,)

Example of Sentence Embedding:

,News ID,Sample Title,Embedding (first 10 dims)
0,N55528,"The Brands Queen Elizabeth, Prince Charles, an...","[-0.0093, 0.0424, 0.0590, 0.0121, 0.0334, 0.01..."

### Tạo vector chủ đề

Gán chủ đề cho từng tiêu đề và hiển thị bản tóm tắt kết quả.

In [14]:
# bertopic_vector = BERTopicVector(models.topic_model)

# topics_vector = bertopic_vector.get_vector(
#     model_context.title_list, model_context.semantic_vector_list
# )
# model_context.topics_vector_list = topics_vector
# bertopic_vector.overview()

# metric, topic, example = bertopic_vector.summary()
# print("\nSummary of BERTopic:")
# display(metric)
# print("\nTopic Information:")
# display(topic)
# print("\nExample of BERTopic:")
# display(example)

**Trained model class**

In [15]:
class BERTopicTrained:

    def __init__(self, model_path="models/bertopic_model"):
        self.model = BERTopic.load(model_path)

    def get_vector(self, title_list, semantic_vector, batch_size=1000):
        result = {}

        for start in range(0, len(title_list), batch_size):
            batch = title_list[start:start + batch_size]

            titles = [item["title"] for item in batch]
            embeddings = np.asarray(
                [semantic_vector[item["news_id"]] for item in batch],
                dtype=np.float32,
            )

            topics, probabilities = self.model.transform(titles, embeddings)

            for item, topic, probability in zip(batch, topics, probabilities):
                result[item["news_id"]] = {
                    "topic": int(topic),
                    "probability": probability,
                }

            print(f"Done: {min(start + batch_size, len(title_list))}/{len(title_list)}")

        return result

In [16]:
# import os

# os.makedirs("models", exist_ok=True)

# bertopic_vector.model.save("models/bertopic_model")
# print("Done")

In [17]:
bertopic_vector = BERTopicTrained()

topics_vector = bertopic_vector.get_vector(
    model_context.title_list, model_context.semantic_vector_list
)
model_context.topics_vector_list = topics_vector

2026-07-24 15:36:52,538 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-24 15:36:58,612 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:36:58,613 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:36:58,688 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:37:17,060 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:37:17,061 - BERTopic - Cluster - Completed ✓
2026-07-24 15:37:17,069 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 1000/51282

2026-07-24 15:37:17,274 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:37:17,275 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:37:17,357 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:37:35,213 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:37:35,214 - BERTopic - Cluster - Completed ✓
2026-07-24 15:37:35,225 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 2000/51282

2026-07-24 15:37:35,453 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:37:35,454 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:37:35,534 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:37:53,233 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:37:53,234 - BERTopic - Cluster - Completed ✓
2026-07-24 15:37:53,243 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 3000/51282

2026-07-24 15:37:53,467 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:37:53,468 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:37:53,550 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:38:11,324 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:38:11,325 - BERTopic - Cluster - Completed ✓
2026-07-24 15:38:11,334 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 4000/51282

2026-07-24 15:38:11,591 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:38:11,592 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:38:11,672 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:38:29,671 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:38:29,671 - BERTopic - Cluster - Completed ✓
2026-07-24 15:38:29,682 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-24 15:38:29,861 - BERTopic - Dimensionality - Completed ✓

Done: 5000/51282

2026-07-24 15:38:29,862 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:38:29,946 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:38:48,150 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:38:48,151 - BERTopic - Cluster - Completed ✓
2026-07-24 15:38:48,161 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 6000/51282

2026-07-24 15:38:48,362 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:38:48,363 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:38:48,434 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:39:06,586 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:39:06,587 - BERTopic - Cluster - Completed ✓
2026-07-24 15:39:06,596 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 7000/51282

2026-07-24 15:39:06,851 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:39:06,853 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:39:06,940 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:39:25,059 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:39:25,060 - BERTopic - Cluster - Completed ✓
2026-07-24 15:39:25,072 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 8000/51282

2026-07-24 15:39:25,266 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:39:25,268 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:39:25,354 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:39:43,954 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:39:43,955 - BERTopic - Cluster - Completed ✓
2026-07-24 15:39:43,965 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 9000/51282

2026-07-24 15:39:44,252 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:39:44,254 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:39:44,328 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:40:04,016 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:40:04,017 - BERTopic - Cluster - Completed ✓
2026-07-24 15:40:04,030 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 10000/51282

2026-07-24 15:40:04,342 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:40:04,344 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:40:04,418 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:40:21,632 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:40:21,632 - BERTopic - Cluster - Completed ✓
2026-07-24 15:40:21,642 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 11000/51282

2026-07-24 15:40:21,891 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:40:21,894 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:40:21,972 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:40:39,629 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:40:39,629 - BERTopic - Cluster - Completed ✓
2026-07-24 15:40:39,640 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-24 15:40:39,830 - BERTopic - Dimensionality - Completed ✓

Done: 12000/51282

2026-07-24 15:40:39,831 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:40:39,899 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:40:57,478 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:40:57,479 - BERTopic - Cluster - Completed ✓
2026-07-24 15:40:57,489 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 13000/51282

2026-07-24 15:40:57,801 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:40:57,802 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:40:57,874 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:41:15,904 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:41:15,905 - BERTopic - Cluster - Completed ✓
2026-07-24 15:41:15,916 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 14000/51282

2026-07-24 15:41:16,167 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:41:16,169 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:41:16,242 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:41:33,846 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:41:33,847 - BERTopic - Cluster - Completed ✓
2026-07-24 15:41:33,864 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 15000/51282

2026-07-24 15:41:34,153 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:41:34,154 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:41:34,230 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:41:54,700 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:41:54,700 - BERTopic - Cluster - Completed ✓
2026-07-24 15:41:54,712 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 16000/51282

2026-07-24 15:41:54,926 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:41:54,927 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:41:55,009 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:42:13,981 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:42:13,982 - BERTopic - Cluster - Completed ✓
2026-07-24 15:42:13,992 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 17000/51282

2026-07-24 15:42:14,193 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:42:14,194 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:42:14,267 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:42:31,889 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:42:31,890 - BERTopic - Cluster - Completed ✓
2026-07-24 15:42:31,901 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 18000/51282

2026-07-24 15:42:32,148 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:42:32,150 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:42:32,224 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:42:50,329 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:42:50,330 - BERTopic - Cluster - Completed ✓
2026-07-24 15:42:50,341 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 19000/51282

2026-07-24 15:42:50,622 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:42:50,624 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:42:50,712 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:43:08,516 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:43:08,517 - BERTopic - Cluster - Completed ✓
2026-07-24 15:43:08,527 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-24 15:43:08,721 - BERTopic - Dimensionality - Completed ✓

Done: 20000/51282

2026-07-24 15:43:08,722 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:43:08,804 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:43:26,255 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:43:26,261 - BERTopic - Cluster - Completed ✓
2026-07-24 15:43:26,272 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 21000/51282

2026-07-24 15:43:26,478 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:43:26,479 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:43:26,559 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:43:44,759 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:43:44,760 - BERTopic - Cluster - Completed ✓
2026-07-24 15:43:44,775 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 22000/51282

2026-07-24 15:43:45,037 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:43:45,038 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:43:45,117 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:44:02,294 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:44:02,295 - BERTopic - Cluster - Completed ✓
2026-07-24 15:44:02,306 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 23000/51282

2026-07-24 15:44:02,543 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:44:02,544 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:44:02,606 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:44:19,656 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:44:19,657 - BERTopic - Cluster - Completed ✓
2026-07-24 15:44:19,667 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 24000/51282

2026-07-24 15:44:19,878 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:44:19,879 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:44:19,949 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:44:37,920 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:44:37,920 - BERTopic - Cluster - Completed ✓
2026-07-24 15:44:37,932 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 25000/51282

2026-07-24 15:44:38,199 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:44:38,200 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:44:38,271 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:44:56,280 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:44:56,281 - BERTopic - Cluster - Completed ✓
2026-07-24 15:44:56,291 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 26000/51282

2026-07-24 15:44:56,548 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:44:56,549 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:44:56,620 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:45:14,577 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:45:14,577 - BERTopic - Cluster - Completed ✓
2026-07-24 15:45:14,588 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 27000/51282

2026-07-24 15:45:14,800 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:45:14,801 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:45:14,873 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:45:32,458 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:45:32,459 - BERTopic - Cluster - Completed ✓
2026-07-24 15:45:32,469 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 28000/51282

2026-07-24 15:45:32,704 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:45:32,705 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:45:32,783 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:45:49,705 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:45:49,706 - BERTopic - Cluster - Completed ✓
2026-07-24 15:45:49,715 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-24 15:45:49,908 - BERTopic - Dimensionality - Completed ✓

Done: 29000/51282

2026-07-24 15:45:49,909 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:45:49,983 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:46:06,840 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:46:06,841 - BERTopic - Cluster - Completed ✓
2026-07-24 15:46:06,853 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 30000/51282

2026-07-24 15:46:07,083 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:46:07,084 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:46:07,155 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:46:24,098 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:46:24,099 - BERTopic - Cluster - Completed ✓
2026-07-24 15:46:24,109 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 31000/51282

2026-07-24 15:46:24,317 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:46:24,318 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:46:24,391 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:46:43,348 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:46:43,349 - BERTopic - Cluster - Completed ✓
2026-07-24 15:46:43,357 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 32000/51282

2026-07-24 15:46:43,615 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:46:43,616 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:46:43,689 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:47:00,593 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:47:00,594 - BERTopic - Cluster - Completed ✓
2026-07-24 15:47:00,603 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 33000/51282

2026-07-24 15:47:00,815 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:47:00,816 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:47:00,895 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:47:18,153 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:47:18,155 - BERTopic - Cluster - Completed ✓
2026-07-24 15:47:18,165 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 34000/51282

2026-07-24 15:47:18,366 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:47:18,367 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:47:18,445 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:47:35,642 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:47:35,643 - BERTopic - Cluster - Completed ✓
2026-07-24 15:47:35,654 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 35000/51282

2026-07-24 15:47:35,890 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:47:35,891 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:47:35,968 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:47:53,334 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:47:53,335 - BERTopic - Cluster - Completed ✓
2026-07-24 15:47:53,345 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 36000/51282

2026-07-24 15:47:53,647 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:47:53,648 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:47:53,717 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:48:10,671 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:48:10,672 - BERTopic - Cluster - Completed ✓
2026-07-24 15:48:10,682 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 37000/51282

2026-07-24 15:48:10,916 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:48:10,918 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:48:10,988 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:48:29,057 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:48:29,058 - BERTopic - Cluster - Completed ✓
2026-07-24 15:48:29,069 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 38000/51282

2026-07-24 15:48:29,326 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:48:29,327 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:48:29,399 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:48:46,971 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:48:46,971 - BERTopic - Cluster - Completed ✓
2026-07-24 15:48:46,982 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 39000/51282

2026-07-24 15:48:47,224 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:48:47,225 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:48:47,297 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:49:04,413 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:49:04,414 - BERTopic - Cluster - Completed ✓
2026-07-24 15:49:04,424 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 40000/51282

2026-07-24 15:49:04,688 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:49:04,689 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:49:04,766 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:49:21,974 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:49:21,974 - BERTopic - Cluster - Completed ✓
2026-07-24 15:49:21,984 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 41000/51282

2026-07-24 15:49:22,220 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:49:22,221 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:49:22,297 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:49:39,828 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:49:39,829 - BERTopic - Cluster - Completed ✓
2026-07-24 15:49:39,839 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 42000/51282

2026-07-24 15:49:40,092 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:49:40,093 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:49:40,167 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:49:57,494 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:49:57,495 - BERTopic - Cluster - Completed ✓
2026-07-24 15:49:57,505 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 43000/51282

2026-07-24 15:49:57,711 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:49:57,712 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:49:57,781 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:50:15,410 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:50:15,410 - BERTopic - Cluster - Completed ✓
2026-07-24 15:50:15,422 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 44000/51282

2026-07-24 15:50:15,640 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:50:15,642 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:50:15,720 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:50:32,904 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:50:32,905 - BERTopic - Cluster - Completed ✓
2026-07-24 15:50:32,915 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 45000/51282

2026-07-24 15:50:33,126 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:50:33,127 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:50:33,188 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:50:50,751 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:50:50,752 - BERTopic - Cluster - Completed ✓
2026-07-24 15:50:50,763 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 46000/51282

2026-07-24 15:50:50,991 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:50:50,992 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:50:51,047 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:51:08,166 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:51:08,167 - BERTopic - Cluster - Completed ✓
2026-07-24 15:51:08,177 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 47000/51282

2026-07-24 15:51:08,433 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:51:08,434 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:51:08,518 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:51:25,508 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:51:25,508 - BERTopic - Cluster - Completed ✓
2026-07-24 15:51:25,520 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 48000/51282

2026-07-24 15:51:25,794 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:51:25,795 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:51:25,867 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:51:43,084 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:51:43,085 - BERTopic - Cluster - Completed ✓
2026-07-24 15:51:43,096 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 49000/51282

2026-07-24 15:51:43,300 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:51:43,302 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:51:43,370 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:52:00,411 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:52:00,412 - BERTopic - Cluster - Completed ✓
2026-07-24 15:52:00,424 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.

Done: 50000/51282

2026-07-24 15:52:00,643 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:52:00,644 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:52:00,696 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN
2026-07-24 15:52:17,565 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:52:17,565 - BERTopic - Cluster - Completed ✓
2026-07-24 15:52:17,575 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-24 15:52:17,638 - BERTopic - Dimensionality - Completed ✓
2026-07-24 15:52:17,639 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-24 15:52:17,659 - BERTopic - Probabilities - Start calculation of probabilities with HDBSCAN

Done: 51000/51282

2026-07-24 15:52:22,576 - BERTopic - Probabilities - Completed ✓
2026-07-24 15:52:22,577 - BERTopic - Cluster - Completed ✓

Done: 51282/51282

Represented vector

In [18]:
class RepresentedVector(Vector):
    def __init__(self, title_list, sentence_dict, bertopic_dict):
        self.title_list = title_list
        self.sentence_dict = sentence_dict
        self.bertopic_dict = bertopic_dict
        self.represented_vector = {}

    def get_vector(self):
        self.represented_vector = {
            news["news_id"]: {
                "title": news["title"],
                "semantic": self.sentence_dict[news["news_id"]],
                # "topic": self.bertopic_dict[news["news_id"]]["topic"],
                "topic_distribution": self.bertopic_dict[news["news_id"]][
                    "probability"
                ],
            }
            for news in self.title_list
        }

        return self.represented_vector

    def overview(self):
        print("=" * 80)
        print("Represented Vector Overview")
        print("=" * 80)

        print(f"Documents           : {len(self.represented_vector)}")

        first_news_id = next(iter(self.represented_vector))

        sample = self.represented_vector[first_news_id]

        print(f"Semantic Dimension  : {len(sample['semantic'])}")
        print(f"Topic Distribution  : {len(sample['topic_distribution'])}")
        print(f"Stored Fields       : {list(sample.keys())}")

        print("=" * 80)

    def preview_vector(vector, preview_dims=4):
        vector = [round(float(x), 4) for x in vector]

        if len(vector) <= preview_dims * 2:
            return vector

        return vector[:preview_dims] + ["..."] + vector[-preview_dims:]

    def summary(self, sample_index=0, preview_dims=4):

        news = self.title_list[sample_index]
        news_id = news["news_id"]

        represented = self.represented_vector[news_id]

        semantic = represented["semantic"]
        probability = represented["topic_distribution"]

        def preview(vector):
            vector = [round(float(x), 4) for x in vector]

            if len(vector) <= preview_dims * 2:
                return vector

            return vector[:preview_dims] + ["..."] + vector[-preview_dims:]

        semantic_preview = preview(semantic)
        probability_preview = preview(probability)

        summary_df = pd.DataFrame(
            {
                "Field": [
                    "News ID",
                    "Title",
                    # "Assigned Topic",
                    "Semantic Dimension",
                    "Topic Distribution Dimension",
                ],
                "Value": [
                    news_id,
                    represented["title"],
                    # represented["topic"],
                    len(semantic),
                    len(probability),
                ],
            }
        )

        represented_preview = {
            news_id: {
                "title": represented["title"],
                "semantic": semantic_preview,
                # "topic": represented["topic"],
                "topic_distribution": probability_preview,
            }
        }

        return summary_df, represented_preview

### Kết hợp các vector

Ghép embedding ngữ nghĩa và phân bố chủ đề thành một biểu diễn cho mỗi tin - Represented Vector.

In [19]:
represented_vector = RepresentedVector(
    model_context.title_list,
    model_context.semantic_vector_list,
    model_context.topics_vector_list,
)

# print(model_context.semantic_vector_list)
# print(model_context.semantic_vector_list)
# print(model_context.topics_vector_list)

represented_vector_list = represented_vector.get_vector()
represented_vector.overview()
represented_vector.summary(sample_index=0, preview_dims=4)

================================================================================
Represented Vector Overview
================================================================================
Documents           : 51282
Semantic Dimension  : 384
Topic Distribution  : 711
Stored Fields       : ['title', 'semantic', 'topic_distribution']
================================================================================

(                          Field  \
 0                       News ID
 1                         Title
 2            Semantic Dimension
 3  Topic Distribution Dimension

                                                Value
 0                                             N55528
 1  The Brands Queen Elizabeth, Prince Charles, an...
 2                                                384
 3                                                711  ,
 {'N55528': {'title': 'The Brands Queen Elizabeth, Prince Charles, and Prince Philip Swear By',
   'semantic': [-0.0093,
    0.0424,
    0.059,
    0.0121,
    '...',
    0.0517,
    -0.1316,
    0.0508,
    -0.0301],
   'topic_distribution': [0.0005,
    0.0005,
    0.0006,
    0.0006,
    '...',
    0.0004,
    0.0004,
    0.0009,
    0.0004]}})

# User Representation Vector

## Prepare sample data User Representation

In [20]:
user_history = behaviours.set_index("user_id")["history"].to_dict()
# print("User mapping: \n", user_history)

NameError: name 'behaviours' is not defined

## Get Represented Vector of 1 user

### Tính vector người dùng

Lấy trung bình vector của các tin trong lịch sử đọc để tạo biểu diễn cho một người dùng.

In [ ]:
class URV:
    def __init__(self, represented_vector, user_behaviours):
        self.represented_vector = represented_vector
        self.user_behaviours = user_behaviours
        self.user_representation_vector = None
        
    def getURV(self, user_id: str):
        user_history_id = self.user_behaviours[user_id].split()
        
        user_history_vector = [
            self.represented_vector[news_id]
            for news_id in user_history_id
        ]

        user_representation_vector = {
                "user_id": user_id,
                "semantic": np.mean(
                    [v["semantic"] for v in user_history_vector],
                    axis=0
                ),
                "topic_distribution": np.mean(
                    [v["topic_distribution"] for v in user_history_vector],
                    axis=0
                )
            }
        
        self.user_representation_vector = user_representation_vector
        
        assert np.allclose(
            np.mean([v["semantic"] for v in user_history_vector], axis=0),
            sum(v["semantic"] for v in user_history_vector) / len(user_history_vector)
        )
        
        return self.user_representation_vector
        
        
urv = URV(represented_vector=represented_vector_list, user_behaviours=user_history)
urv.getURV("U10339")

#   Recommendation Engine

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

def cosine(v1, v2):
    return cosine_similarity(
        v1.reshape(1, -1),
        v2.reshape(1, -1)
    )[0][0]
    
sample_user_vector = urv.getURV("U79199")

In [ ]:
display(sample_user_vector["topic_distribution"])

In [ ]:
class RecommendationEngine:
    def __init__(self, represented_vector, alpha=0.5):
        self.represented_vector = represented_vector
        self.alpha = alpha
        self.score = lambda semantic, topic: self.alpha * semantic + (1 - self.alpha) * topic

    def calculate_similarity(self, user_vector, news_vector):
        semantic = cosine(
            user_vector["semantic"],
            news_vector["semantic"]
        )

        topic = cosine(
            user_vector["topic_distribution"],
            news_vector["topic_distribution"]
        )

        return self.score(semantic, topic), semantic, topic

    def recommend(self, user_vector, candidate_news):
        news_vector = [self.represented_vector[i] for i in candidate_news]
        scores = []
        
        for news_id in candidate_news:
            score, semantic_score, topic_score = self.calculate_similarity(
                user_vector,
                self.represented_vector[news_id]
            )

            scores.append((news_id, score, semantic_score, topic_score))
                
        scores.sort(key=lambda x: x[1], reverse=True)
        display(scores)
        
        

sample = RecommendationEngine(represented_vector_list)
sample.recommend(user_vector=sample_user_vector, candidate_news=["N51048", "N64094", "N13907", "N39010", "N37083", "N459"])